version: '3.7'

services:
  gateway_service:
    build: ./gateway
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./gateway/:/app/
    ports:
      - 8001:8000
    environment:
      - WALLET_SERVICE_HOST_URL=http://wallet_service:8000/api/v1/wallet/
      - DISCOUNT_SERVICE_HOST_URL=http://discount_service:8000/api/v1/discount/


  wallet_service:
    build: ./wallet
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./wallet/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://${WALLET_DB_USERNAME}:${WALLET_DB_PASSWORD}@wallet_db/${WALLET_DB_NAME}
    depends_on:
      - wallet_db

  wallet_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_wallet:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${WALLET_DB_USERNAME}
      - POSTGRES_PASSWORD=${WALLET_DB_PASSWORD}
      - POSTGRES_DB=${WALLET_DB_NAME}
    env_file:
      - .env

  discount_service:
    build: ./discount
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./discount/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://${DISCOUNT_DB_USERNAME}:${DISCOUNT_DB_PASSWORD}@discount_db/${DISCOUNT_DB_NAME}
      - WALLET_SERVICE_HOST_URL=http://wallet_service:8000/api/v1/wallet/
    depends_on:
      - redis_server
      - discount_db
      - wallet_service

  discount_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_discount:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DISCOUNT_DB_USERNAME}
      - POSTGRES_PASSWORD=${DISCOUNT_DB_PASSWORD}
      - POSTGRES_DB=${DISCOUNT_DB_NAME}
    env_file:
      - .env

  redis_server:
    restart: on-failure
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379


volumes:
  postgres_data_wallet:
  postgres_data_discount: